@ECHO OFF
CLS
%~dp0php\test_learn.php
%~dp0php\test_base_status.php
%~dp0php\test_status.php
%~dp0php\test_full_status.php
%~dp0php\test_cash_in.php
%~dp0php\test_cash_out.php
%~dp0php\test_print_demo.php
%~dp0php\test_print_fn_registrations.php
%~dp0php\test_print_info.php
%~dp0php\test_print_non_fiscal_doc.php
%~dp0php\test_print_ofd_exchange_status.php
%~dp0php\test_print_ofd_test.php
%~dp0php\test_sell.php
%~dp0php\test_sell_return.php
%~dp0php\test_print_last_document.php
%~dp0php\test_report_x.php
%~dp0php\test_close_shift.php
%~dp0php\test_cash_stat.php
%~dp0php\test_print_close_shift_reports.php
%~dp0php\test_reset_state.php
